### ISSUE TITLE
Failed to activate the language-gamescript package

### ISSUE THREAD

**Issue by alex-fgsfds** [agmike/atom-language-gamescript#4]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.7
**System**: Unknown Windows Version
**Thrown From**: [language-gamescript](https://github.com/agmike/atom-language-gamescript) package, v0.3.1
### Stack Trace

Failed to activate the language-gamescript package

```
At Cannot find module 'filewalker'

Error: Cannot find module 'filewalker'
  at Module._resolveFilename (module.js:328:15)
  at Function.Module._resolveFilename (C:\Users\Александр\AppData\Local\atom\app-1.0.7\resources\app.asar\src\module-cache.js:383:52)
  at Function.Module._load (module.js:270:25)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (C:\Users\Александр\.atom\packages\atom-language-gamescript\lib\linter-gamescript.coffee:3:14)
  at Object.<anonymous> (C:\Users\Александр\.atom\packages\atom-language-gamescript\lib\linter-gamescript.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (C:\Users\Александр\AppData\Local\atom\app-1.0.7\resources\app.asar\node_modules\coffee-cash\lib\coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.module.exports.provideLinter (C:\Users\Александр\.atom\packages\atom-language-gamescript\lib\init.coffee:39:24)
  at Package.module.exports.Package.activateServices (C:\Users\Александр\AppData\Local\atom\app-1.0.7\resources\app.asar\src\package.js:414:69)
  at Package.module.exports.Package.activateNow (C:\Users\Александр\AppData\Local\atom\app-1.0.7\resources\app.asar\src\package.js:246:16)
  at C:\Users\Александр\AppData\Local\atom\app-1.0.7\resources\app.asar\src\package.js:224:30
  at Package.module.exports.Package.measure (C:\Users\Александр\AppData\Local\atom\app-1.0.7\resources\app.asar\src\package.js:167:15)
  at Package.module.exports.Package.activate (C:\Users\Александр\AppData\Local\atom\app-1.0.7\resources\app.asar\src\package.js:216:14)
  at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\Александр\AppData\Local\atom\app-1.0.7\resources\app.asar\src\package-manager.js:486:21)
  at C:\Users\Александр\AppData\Local\atom\app-1.0.7\resources\app.asar\src\package-manager.js:469:29
  at Config.module.exports.Config.transact (C:\Users\Александр\AppData\Local\atom\app-1.0.7\resources\app.asar\src\config.js:311:16)
  at PackageManager.module.exports.PackageManager.activatePackages (C:\Users\Александр\AppData\Local\atom\app-1.0.7\resources\app.asar\src\package-manager.js:464:19)
  at PackageManager.module.exports.PackageManager.activate (C:\Users\Александр\AppData\Local\atom\app-1.0.7\resources\app.asar\src\package-manager.js:445:46)
  at Atom.module.exports.Atom.startEditorWindow (C:\Users\Александр\AppData\Local\atom\app-1.0.7\resources\app.asar\src\atom.js:673:21)
  at Object.<anonymous> (C:\Users\Александр\AppData\Local\atom\app-1.0.7\resources\app.asar\src\window-bootstrap.js:12:8)
  at Object.<anonymous> (C:\Users\Александр\AppData\Local\atom\app-1.0.7\resources\app.asar\src\window-bootstrap.js:23:4)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (C:\Users\Александр\AppData\Local\atom\app-1.0.7\resources\app.asar\src\babel.js:163:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at setupWindow (file:///C:/Users/%D0%90%D0%BB%D0%B5%D0%BA%D1%81%D0%B0%D0%BD%D0%B4%D1%80/AppData/Local/atom/app-1.0.7/resources/app.asar/static/index.js:96:23)
  at window.onload (file:///C:/Users/%D0%90%D0%BB%D0%B5%D0%BA%D1%81%D0%B0%D0%BD%D0%B4%D1%80/AppData/Local/atom/app-1.0.7/resources/app.asar/static/index.js:36:7)

```
### Commands

```
```
### Config

``` json
{}
```
### Installed Packages

``` coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by agmike** [comment]
Please install via `Settings -> Install Packages` or `apm install language-gamescript`.
